# Generated by Django 5.0.4 on 2024-04-25 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('username', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'expense',
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expense_tracker.user'),
        ),
    ]
