# Generated by Django 5.0.4 on 2024-04-25 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0003_expense_delete_transaction_alter_user_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
